apply plugin: plugs.android.lib
apply plugin: plugs.kotlin.android

android {
    namespace 'lib.um'
    compileSdk versions.compileSdk
    buildToolsVersion versions.buildTools

    defaultConfig {
        minSdk versions.minSdk
        targetSdk versions.compileSdk
        versionCode versions.versionCode
        versionName versions.versionName

        manifestPlaceholders = [
                qqappid : "",
        ]
    }
}

buildscript {
    ext.um = [
            platform: '7.1.4',
    ]
}

dependencies {
    api fileTree(dir: "libs", include: ["*.jar"])

    implementation project(deps.lib.vector.core)

    api 'com.umeng.umsdk:common:9.5.0'
    api 'com.umeng.umsdk:asms:1.6.3'
    api "com.umeng.umsdk:share-core:$um.platform"
    api "com.umeng.umsdk:share-qq:$um.platform"
    api "com.umeng.umsdk:share-wx:$um.platform"
    api "com.umeng.umsdk:share-sina:$um.platform"
    api "com.umeng.umsdk:share-board:$um.platform"

    //微博官方SDK
//    implementation 'com.sina.weibo.sdk:core:10.10.0:openDefaultRelease@aar'
    implementation project(deps.dsb.lib.umeng_aars)
    //微信官方依赖库
    implementation 'com.tencent.mm.opensdk:wechat-sdk-android-without-mta:6.6.5'
    //QQ官方依赖库
    implementation 'com.tencent.tauth:qqopensdk:3.51.2'
}