# https://developer.android.google.cn/jetpack/androidx/versions
[versions]
core = "1.15.0"
appcompat = '1.7.0'
fragment = '1.8.5'
preference = '1.2.1'
activity = '1.10.1'

annotation = '1.9.1'
annotation-experimental = '1.4.1'

recyclerview = '1.3.2'
gridlayout = '1.0.0'
cardview = '1.0.0'
swiperefresh = '1.2.0-alpha01'
constraintLayout = '2.2.0'
constraintLayout-compose = '1.1.0'
viewpager2 = '1.1.0'

media = '1.7.0'
media2 = '1.3.0'
media3 = '1.5.1'

room = '2.7.0-rc02'
sqlite = '2.4.0'
datastore = '1.1.4'

dex = '2.0.1'
exifinterface = '1.4.0'
webkit = '1.10.0'

vectorDrawalbe = '1.2.0'
vectorDrawalbe-seekable = '1.0.0'

lifecycle = '2.8.7'

work = '2.10.0'
startup = '1.2.0'
tracing = '1.2.0'
camera = '1.4.1'
paging = '3.3.6'
navigation = "2.8.6"

# ====libraries====
[libraries]
core-java = { module = "androidx.core:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
core-role = { module = "androidx.core:core-role", version = "1.1.0-rc01" }
animation = { module = "androidx.core:animation", version = "1.0.0" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
fragment-compose = { module = "androidx.fragment:fragment-compose", version.ref = "fragment" }

preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }

activity = { module = "androidx.activity:activity", version.ref = "activity" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
annotation-experimental = { module = "androidx.annotation:annotation-experimental", version.ref = "annotation-experimental" }

legacy-v4 = { module = "androidx.legacy:legacy-support-v4", version = "1.0.0" }

recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
swiperefresh = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefresh" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
constraintLayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayout-compose" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }

dex = { module = "androidx.multidex:multidex", version.ref = "dex" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "room" }
room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-gradlePlugin = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }

datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
datastore-preferences-proto = { module = "androidx.datastore:datastore-preferences-proto", version.ref = "datastore" }
datastore-proto = { module = "androidx.datastore:datastore", version.ref = "datastore" }

vectorDrawable-runtime = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vectorDrawalbe" }
vectorDrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "vectorDrawalbe" }
vectorDrawable-seekable = { module = "androidx.vectordrawable:vectordrawable-seekable", version.ref = "vectorDrawalbe-seekable" }

media = { module = "androidx.media:media", version.ref = "media" }

# https://developer.android.google.cn/jetpack/androidx/releases/media2?hl=zh-cn
media2-session = { module = "androidx.media2:media2-session", version.ref = "media2" }
media2-widget = { module = "androidx.media2:media2-widget", version.ref = "media2" }
media2-player = { module = "androidx.media2:media2-player", version.ref = "media2" }

# https://developer.android.google.cn/jetpack/androidx/releases/media3?hl=zh-cn
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
media3-player = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }

lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" } # ProcessLifeCycleOwner
lifecycle-reactivestreams = { module = "androidx.lifecycle:lifecycle-reactivestreams-ktx", version.ref = "lifecycle" }
lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle" }

work-runtime = { module = "androidx.work:work-runtime", version.ref = "work" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
work-rxjava2 = { module = "androidx.work:work-rxjava2", version.ref = "work" }
work-gcm = { module = "androidx.work:work-gcm", version.ref = "work" }
work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "work" }

startup = { module = "androidx.startup:startup-runtime", version.ref = "startup" }
tracing = { module = "androidx.tracing:tracing", version.ref = "tracing" }

camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-video = { module = "androidx.camera:camera-video", version.ref = "camera" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }
camera-mlkit-vision = { module = "androidx.camera:camera-mlkit-vision", version.ref = "camera" }
camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camera" }

paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }
paging-rxjava2 = { module = "androidx.paging:paging-rxjava2", version.ref = "paging" }
paging-rxjava3 = { module = "androidx.paging:paging-rxjava3", version.ref = "paging" }
# alternatively - without Android dependencies for testing
paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
# optional - Guava ListenableFuture support
paging-guava = { module = "androidx.paging:paging-guava", version.ref = "paging" }
# optional - Jetpack Compose integration
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }

navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-feature = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigation" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }


# ====plugins====
[plugins]
room = { id = "androidx.room", version.ref = "room" }

navigation = { id = "androidx.navigation.safeargs", version.ref = "navigation" }
# Alternatively, to generate Kotlin code suitable for Kotlin-only modules
navigation-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }


# ====bundles====
[bundles]
lifecycle = [
    "lifecycle-runtime",
    "lifecycle-runtime-ktx",
    "lifecycle-common",
    "lifecycle-viewmodel-ktx",
    "lifecycle-viewmodel-compose",
    "lifecycle-livedata",
    "lifecycle-service",
    #    "lifecycle-process",
    #    "lifecycle-reactivestreams",
    #    "lifecycle-compiler",
]