# https://developer.android.google.cn/jetpack/androidx/releases/compose?hl=zh-cn
[versions]
compose = '1.7.8'
material3 = '1.3.2'
material3-adaptive = '1.1.0'
compiler = '1.5.15'

[libraries]
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }

# ui
ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
ui-test = { module = "androidx.compose.ui:ui-test", version.ref = "compose" }
ui-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

# foundation
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }

# material
material-iconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3-navigationSuite = { module = "androidx.compose.material3:material3-navigation-suite", version.ref = "material3" }
material3-windowSizeClass = { module = "androidx.compose.material3:window-size-class", version.ref = "material3" }
material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "material3-adaptive" }
material3-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "material3-adaptive" }
material3-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "material3-adaptive" }
