# aop相关的库都会列在这, 比如aspectj或者asm或者其他三方库
[versions]
# https://github.com/eclipse-aspectj/aspectj
aspectj = "1.9.22.1"
# https://github.com/Ibotta/gradle-aspectj-pipeline-plugin
# ibotta = "1.4.1" // 项目不再维护了
asm = "9.7"

# ====libraries====
[libraries]
aspectj-jrt = { module = "org.aspectj:aspectjrt", version.ref = "aspectj" }
aspectj-weaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj" }
aspectj-tools = { module = "org.aspectj:aspectjtools", version.ref = "aspectj" }
aspectj-matcher = { module = "org.aspectj:aspectjmatcher", version.ref = "aspectj" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }