[versions]
material = "1.10.0"
# ksp版本:https://github.com/google/ksp
ksp = "2.1.20-2.0.0"
gson = '2.13.0'
playServices = '21.3.0'

# protobuf版本: https://central.sonatype.com/namespace/com.google.protobuf
protobuf-lite = '3.0.1'
protobuf-protoc-lite = '3.0.0'
protobuf = "4.30.2"
protobufPlugin = "0.9.5"

# https://firebase.google.com/support/release-notes/android#firestore_v25-1-3
# https://firebase.google.com/docs/android/setup?hl=en
filebase-bom = "33.12.0"
firebase-crashlytics-plugin = "3.0.2"

dagger = '2.56.2'

# ====libraries====
[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

dagger-runtime = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

# 在java项目里调用安卓编译环境
java-android = { module = "com.google.android:android", version = "4.1.1.4" }

# 自动构建Processor等服务环境
auto-service = { module = "com.google.auto.service:auto-service", version = "1.1.1" }
auto-common = { module = "com.google.auto:auto-common", version = "1.2.2" }

flexbox = { module = "com.google.android:flexbox", version = "1.1.0" }

gms-base = { module = "com.google.android.gms:play-services-base", version = "18.7.0" }
gms-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServices" }
gms-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServices" }
gms-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServices" }
gms-auth-base = { module = "com.google.android.gms:play-services-auth-base", version = "18.1.0" }
gms-auth-api-phone = { module = "com.google.android.gms:play-services-auth-api-phone", version = "18.2.0" }
gms-tasks = { module = "com.google.android.gms:play-services-tasks", version = "18.3.0" }

places = { module = "com.google.android.libraries.places:places", version = "3.0.0" }
places-compat = { module = "com.google.android.libraries.places:places-compat", version = "2.6.0" }

maps-utils = { module = "com.google.maps.android:android-maps-utils", version = "0.5" }

zxing = { module = "com.google.zxing:core", version = "3.4.1" }

guava-android = { module = "com.google.guava:guava", version = "33.4.8-android" }
guava-jre = { module = "com.google.guava:guava", version = "33.4.8-jre" }

# protobuf
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobuf-lite = { module = "com.google.protobuf:protobuf-lite", version.ref = "protobuf-lite" }
protobuf-protoc-gen = { module = "com.google.protobuf:protoc-gen-javalite", version.ref = "protobuf-protoc-lite" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "filebase-bom" }
#firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
#firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-crashlytics-gradlePlugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-plugin" }

# ====plugins====
[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
