[versions]
# https://github.com/square/okhttp
okhttp3 = '4.12.0'
retrofit = '2.11.0'


# ====libraries====
[libraries]
okhttp3-ok = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3-tls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp3" }
okhttp3-sse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "okhttp3" }
okhttp3-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
okhttp3-webserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp3" }

retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

okio = { module = "com.squareup.okio:okio", version = "3.11.0" }
# https://github.com/square/leakcanary
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "3.0-alpha-8" }
# https://github.com/square/javapoet, 项目不再维护了
# javapoet = { module = "com.squareup:javapoet", version = "1.13.0" }
# https://github.com/palantir/javapoet
javapoet = { module = "com.palantir.javapoet:javapoet", version = "0.7.0" }
# https://github.com/square/kotlinpoet
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "2.1.0" }
picasso = { module = "com.squareup.picasso:picasso", version = "2.71828" }
seismic = { module = "com.squareup:seismic", version = "1.0.3" }