[versions]
junit5 = '5.12.2'
# https://github.com/mockito/mockito
mockito = '5.17.0'
androidx-espresso = '3.6.1'
androidx-junit = '1.2.1'


# ====libraries====
[libraries]
# https://developer.android.google.cn/jetpack/androidx/releases/test
androidx-core = { module = "androidx.test:core", version = "1.6.1" }
androidx-ktx = { module = "androidx.test:core-ktx", version = "1.6.1" }
androidx-rules = { module = "androidx.test:rules", version = "1.6.1" }
androidx-runner = { module = "androidx.test:runner", version = "1.6.2" }
# androidTestUtil
androidx-orchestrator = { module = "androidx.test:orchestrator", version = "1.4.2" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-espresso-web = { module = "androidx.test.espresso:espresso-web", version.ref = "androidx-espresso" }
androidx-ext-truth = { module = "androidx.test.ext:truth", version = "1.6.0" }
androidx-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-junit" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito:mockito-kotlin", version.ref = "mockito" }

junit4 = { module = "junit:junit", version = "4.13.2" }

junit5-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
junit5-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }

# UI测试框架
robotelectric = { module = "org.robolectric:robolectric", version = "4.14.1" }